import Head from "next/head";
import Blog from "../components/Blog";
import ContentWrapper from "../components/ContentWrapper";
import Footer from "../components/Footer";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";

const URL = process.env.STRAPIBASEURL;
export async function getStaticProps(context) {
  const fetchParams = {
    method: "post",
    headers: {
      "content-type": "application/json",
    },
    body: JSON.stringify({
      query: `{
        blogposts {
          data {
            attributes {
              title
              blogbody
              description
              slug
              splash {
                data {
                  attributes {
                    url
                  }
                }
              }
            }

          }
      }
      }
      `,
    }),
  };

  const res = await fetch(`${URL}/graphql`, fetchParams);
  const { data } = await res.json();

  return {
    props: data,
    revalidate: 10,
  };
}

export default function Home({ blogposts }) {
  return (
    <ContentWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Slax.kit!</a>
        </h1>

        <div className={styles.grid}>
          {blogposts.data.map((data, i) => {
            {
              /* console.log(data.attributes);   */
            }
            const { title, description, slug } = data.attributes;

            return (
              <Blog
                title={title}
                description={description}
                slug={slug}
                key={i}
              />
            );
          })}
        </div>
      </main>
      <Footer />
    </ContentWrapper>
  );
}
